language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3
install:
  - pip install flake8
  - pip install coverage
  - pip install coveralls
  - pip install mock
  - pip install nose
script:
  - nosetests tests --with-coverage --cover-package=git_edit_index --cover-erase
  - flake8 --ignore=E501 git-edit-index tests/git_edit_index_tests.py setup.py
after_success:
  - coveralls
